ALTER TABLE "studios"
  ADD COLUMN IF NOT EXISTS "depositEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "depositType" TEXT NOT NULL DEFAULT 'PERCENTAGE',
  ADD COLUMN IF NOT EXISTS "depositValue" DOUBLE PRECISION NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS "depositExpiryHours" INTEGER NOT NULL DEFAULT 24,
  ADD COLUMN IF NOT EXISTS "whatsappEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "whatsappPhoneNumberId" TEXT,
  ADD COLUMN IF NOT EXISTS "whatsappAccessToken" TEXT,
  ADD COLUMN IF NOT EXISTS "emailEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "emailFromName" TEXT,
  ADD COLUMN IF NOT EXISTS "emailFromAddress" TEXT;
